### ISSUE TITLE
Support YAML artifact import

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-artifact-library#18]
This library currently supports YAML as an export format for artifacts. 

Add support for YAML import of artifacts.

**Comment by martinjoconnor** [comment]
Example YAML serialization of a template (not finalized, but should be close to this):

```
template: Study
     description: Study template
     identifier: SFY343
     version: 1.0.0
     status: published
    
     children:
    
       - field: Study Name
         description: Study name field
         inputType: textfield
         datatype: xsd:string
         required: true
    
       - field: Study ID
         description: Study ID field
         inputType: textfield
         datatype: xsd:string
         required: true
         minLength: 2
    
       - element: Address
         description: Address element
         isMultiple: true
         minItems: 0
         maxItems: 4
    
         children:
           - field: Address 1
             inputType: textfield
             datatype: xsd:string
           - field: ZIP
             inputType: textfield
             datatype: xsd:string
             minLength: 5
             maxLength: 5
```
