### ISSUE TITLE
YAML serialization completion

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-artifact-library#21]
The following list from Atti details the outstanding renderings to be implemented to complete the YAML serialization of schema artifacts:

```
     Template header and footer are missing . See template-007. I am using:
                modelVersion: 1.6.0
                header: Template header
                footer: Template footer
                createdOn: 2024-02-29T14:25:48-08:00
 
     Static fields are not serialized properly, or at all. See template-004, template-009
 
     Regex not serialized for text fields. See template-008
 
     Provenance not serialized. Any template. I am using:
                createdOn: 2024-03-11T15:26:26-07:00
                createdBy: https://metadatacenter.org/users/c7dcc3ca-55fe-4ca8-b448-ab110bfe4c95
                lastUpdatedOn: 2024-03-11T15:26:26-07:00
                modifiedBy: https://metadatacenter.org/users/c7dcc3ca-55fe-4ca8-b448-ab110bfe4c95
 
     Annotations not serialized. see template-027
                annotations:
                  - name: https://datacite.com/doi
                    type: id
                    value: https://doi.org/10.82658/8vc1-qf27
 
           or see field-001
                annotations:
                  - name: https://datacite.com/doi
                    type: id
                    value: https://doi.org/10.82658/8vc1-abcd
                  - name: foo
                    type: value
                    value: bar
 
 
 
     If the child name in properties is different than the schema:name, only the child name is used in yaml.
           See template-26.
           I added "key" as the first attribute. Then we have name. And altLabel
           Name and key should be equal.
           But they are not always
                children:
                  - key: _text_field_
                    type: templateField
                    id: https://repo.metadatacenter.org/template-fields/9efde92f-63b9-427f-b071-36ea57de1b7e
                    name: Textfield
                    description: Help Text
                    modelVersion: 1.6.0
                    inputType: textfield
                    datatype: xsd:string
 
 
     timeFormat: 12h is serialized, even if it is not in the JSON. See template-010
                the field "Simple date" does not have inputTimeFormat in the source json (only 2 occurrences) but the resulting YAML has 3
 
     checkbox currently has these. Do we need them? see template-018
               multiple: true
               minItems: 1
               multipleChoice: true
           for checkbox, these values are always like this.
 
     list: if it is not multiple choice, it does not say it in the YAML. The json says that template-019
           maybe, just for clarity, it should say
                multipleChoice: true
 
     list: if it is multiple, it says so in the JSON and the YAML, this is ok. See template-020
           plus also specifies
                         multiple: true
                         minItems: 1
           are these needed?
 
     attribute-value See template-022. Do we need to say these?
               multiple: true
               minItems: 0
```
